x = int(input('Write how many cups of coffee you will need:'))
print('For', x, 'cups of coffee you will need:')
print(x * 200, 'ml of water')
print(x * 50, 'ml of milk')
print(x * 15, 'g of coffee beans')